services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres: 
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

 
  angular-app:
    build:
      context: ./angular-app
      dockerfile: Dockerfile.angular-app
    ports:
      - "4200:80"  # Mapeia a aplicação Angular para a porta 4200
    depends_on:
      - spring-app

volumes:
  pgdata:
