spring:
  application:
    name: spring-app
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect